# Generated by Django 4.0.1 on 2022-01-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ritwik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='perma_pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='pres_pin',
            field=models.IntegerField(),
        ),
    ]
