# Generated by Django 4.0.1 on 2022-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_member_ritwik_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='mail@demo.com', max_length=254),
        ),
    ]
