# Generated by Django 4.0.1 on 2022-01-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.IntegerField(default='0123456789'),
        ),
    ]
